#!/usr/bin/env python3
"""Make AVIF and AV1 copies of the site's web media + assets/media-formats.js.

    python scripts/build_web_formats.py

Run it last, after build_assets.py / build_curated_media.py /
optimize_web_media.py. For every web still (img-NN, thumb-NN, vid-NN-poster,
c-*.jpg) it writes a sibling .avif, and for every clip (vid-NN.mp4, c-*.mp4) a
sibling AV1 .webm. Measured on this site's own media at matched quality (SSIM),
AVIF came out about a third smaller than JPEG (WebP only about a fifth, so it
is not made), and AV1 28-57% smaller than the H.264 it sits beside.

The originals stay. Pages ask for the new formats first and fall back to the
JPEG / MP4 where a browser cannot decode them, so nothing breaks on an old
Safari. A copy is only kept -- and only listed -- if it is actually smaller,
and assets/media-formats.js lists exactly the files that have one, so a page
never asks for a sibling that is not there.

Copies newer than their source are skipped, so a rerun only does new work.
"""
import json
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_assets import FFMPEG  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"

STILL = re.compile(r"^(img-\d+|thumb-\d+|vid-\d+-poster|c-.+)\.jpg$")
CLIP = re.compile(r"^(vid-\d+|c-.+)\.mp4$")
AVIF_CRF = "28"   # matched the JPEGs' SSIM in testing
AV1_CRF = "38"


def ff(args):
    r = subprocess.run([FFMPEG, "-y", "-hide_banner", "-loglevel", "error", *args],
                       capture_output=True, text=True)
    if r.returncode:
        print("    ffmpeg FAILED:", r.stderr.strip()[:300])
    return r.returncode == 0


def fresh(dst, src):
    return dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime


def avif(src: Path):
    dst = src.with_suffix(".avif")
    if not fresh(dst, src):
        ff(["-i", str(src), "-vf", "format=yuv420p", "-c:v", "libaom-av1", "-still-picture", "1",
            "-crf", AVIF_CRF, "-cpu-used", "6", "-frames:v", "1", str(dst)])
    return keep(src, dst)


# Grainy night footage comes out of AV1 at AV1_CRF bigger than the H.264 it
# sits beside -- the grain is what the bits go on -- so those clips had no
# small copy at all, and they are the heaviest on the site. For them a second
# pass: a higher CRF with the grain taken out and synthesised back on
# playback. Checked by eye against the MP4 on the Rained In clip: 7.5 MB to
# 4.0 MB with no visible difference at page size.
AV1_CRF_GRAINY = "50"


def av1_encode(src, dst, crf, extra=""):
    ff(["-i", str(src), "-c:v", "libsvtav1", "-preset", "6", "-crf", crf,
        "-pix_fmt", "yuv420p", "-svtav1-params", "enable-overlays=1" + extra,
        "-c:a", "libopus", "-b:a", "64k", str(dst)])


def av1(src: Path):
    dst = src.with_suffix(".webm")
    if not fresh(dst, src):
        av1_encode(src, dst, AV1_CRF)
        if dst.exists() and dst.stat().st_size >= src.stat().st_size:
            print(f"    {src.name}: grainy, second pass")
            av1_encode(src, dst, AV1_CRF_GRAINY, ":film-grain=8")
    return keep(src, dst)


def keep(src, dst):
    if dst.exists() and dst.stat().st_size and dst.stat().st_size < src.stat().st_size:
        return src.relative_to(ROOT).as_posix(), src.stat().st_size, dst.stat().st_size
    dst.unlink(missing_ok=True)
    return None


def main():
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    files = [p for p in sorted(ASSETS.glob("*/*/*")) if "NewAssets" not in p.parts]
    stills = [p for p in files if STILL.match(p.name)]
    clips = [p for p in files if CLIP.match(p.name)]
    print(f"{len(stills)} stills, {len(clips)} clips")
    with ThreadPoolExecutor(max_workers=4) as pool:
        a = [r for r in pool.map(avif, stills) if r]
    with ThreadPoolExecutor(max_workers=2) as pool:
        v = [r for r in pool.map(av1, clips) if r]

    index = {"avif": sorted(r[0] for r in a), "av1": sorted(r[0] for r in v)}
    js = ("// generated by scripts/build_web_formats.py -- do not hand-edit.\n"
          "// The .jpg files that have a smaller .avif beside them, and the .mp4\n"
          "// files that have a smaller AV1 .webm. Pages only ask for these.\n"
          "const MEDIA_FORMATS = " + json.dumps(index, indent=1) + ";\n")
    (ASSETS / "media-formats.js").write_text(js, encoding="utf-8")
    for name, rows in (("AVIF", a), ("AV1", v)):
        before = sum(r[1] for r in rows) // 1024
        after = sum(r[2] for r in rows) // 1024
        print(f"{name}: {len(rows)} files, {before} KB -> {after} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
