#!/usr/bin/env python3
"""Generate one standalone page per project into projects/<slug>.html.

Every project in assets/manifest.js gets its own real HTML file with its own
URL, all cut from the same template below. The pages are thin shells: the
title, category tag, back link and project key are baked in here, and
assets/render-project.js fills in the media, text and prev/next arrows at load
time from assets/manifest.js + assets/project-details.js + assets/page-config.js.

Run after adding/renaming a project (and after `python scripts/build_assets.py`):

    python scripts/build_project_pages.py

Pages whose project no longer exists in the manifest are deleted, but only if
they still carry the generated-file marker, so anything hand-written in
projects/ is left alone.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = ROOT / "assets"
OUT_DIR = ROOT / "projects"

MARKER = "<!-- generated by scripts/build_project_pages.py — edits here are overwritten -->"

# Section key in assets/page-config.js -> the list page it renders on.
SECTION_PAGES = {
    "work": ("work.html", "work"),
    "play": ("play.html", "play"),
    # GMMBBQ sits under play rather than beside it: it gets its own list page
    # and its own back link, but not a slot in the section nav and not a
    # colour of its own -- it runs on play's magenta.
    "gmmbbq": ("gmmbbq.html", "gmmbbq"),
    "facilitation": ("facilitation.html", "facilitation"),
}

# Projects that are off the site but still in the manifest, because their
# media and their source folders are untouched and taking them off was an
# editorial call rather than a deletion. Listing one here is what actually
# removes it: dropping it from assets/page-config.js only unlists it, and its
# page stays reachable at its own URL. The stale-page sweep at the end of
# main() deletes the file on the next run, and putting a project back is a
# matter of taking its key out of this set.
RETIRED = {
    "gmmbbq/midroom",
    "gmmbbq/tychostones",
}

# Absolute, because a link scraper has no base to resolve a relative URL
# against. One constant to change if the site ever gets its own domain.
SITE_URL = "https://jishnurc519.github.io/Portfolio2025"
# The link preview for anything without a picture of its own: the wordmark.
SHARE_IMAGE = SITE_URL + "/assets/og-wordmark.png"

# Pages that are not project pages, for sitemap.xml.
SITE_PAGES = ["", "work.html", "play.html", "facilitation.html", "gmmbbq.html"]

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
{marker}
<head>
  <meta charset="utf-8" />
  <!-- Pages live in projects/, so every relative path below (and every path in
       assets/manifest.js) resolves against the site root. -->
  <base href="../">
  <title>Jishnu Roy Chaudhury — {title}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="description" content="{description}" />{robots}
  <link rel="icon" href="assets/favicon.svg" type="image/svg+xml">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="jishnu has an artpage">
  <meta property="og:title" content="{title} — Jishnu Roy Chaudhury">
  <meta property="og:description" content="{description}">
  <meta property="og:url" content="{site_url}/projects/{slug}.html">
  <meta property="og:image" content="{share_image}">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="preconnect" href="https://api.fontshare.com">
  <link href="https://api.fontshare.com/css?f[]=clash-display@200,400,600,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/project-page.css">
  <script src="assets/site-bar.js" defer></script>
</head>
<body data-project="{key}">

  <!-- The way out is the wordmark in the corner (home) and work / play /
       learn across the top, both from assets/site-bar.js; the keys 1 2 3 do
       the same without the mouse. -->

  <div id="main-wrapper" role="main">
    <div id="header-section">
      <span class="category-tag">{category}</span>
      <h1>{title}</h1>
      <div class="meta-row" id="meta-row"></div>
    </div>

    <p class="overview" id="project-overview">{overview}</p>
    <!-- The finished film, where there is one, and then the write-up, and
         only then the stills. The gallery used to sit directly under the
         overview, so a reader met eight photographs of how a thing was made
         before one line saying what it was. The work itself is not evidence
         of the work, though, so the film keeps the top slot. -->
    <div id="project-film"></div>
    <div id="extra-sections"></div>
    <div class="gallery" id="project-gallery"></div>
    <noscript>
      <p class="empty-state">This project&#39;s media and write-up are assembled in the
      browser. With scripts off, the links above still work.</p>
    </noscript>
    <nav class="project-pager" id="project-pager"></nav>
  </div>

  <div id="lightbox" role="dialog" aria-modal="true" aria-label="Enlarged image" aria-hidden="true">
    <button type="button" class="lightbox-close" aria-label="Close image">×</button>
    <img src="" alt="">
  </div>

  <script src="assets/manifest.js"></script>
  <script src="assets/curated-media.js"></script>
  <script src="assets/media-formats.js"></script>
  <script src="assets/diagrams.js"></script>
  <script src="assets/project-details.js"></script>
  <script src="assets/page-config.js"></script>
  <script src="assets/keys.js"></script>
  <script src="assets/cursor.js"></script>
  <script src="assets/render-project.js"></script>
</body>
</html>
"""


def load_manifest() -> dict:
    """assets/manifest.js is `const SITE_MANIFEST = {...};` — strip and parse."""
    text = (ASSETS_DIR / "manifest.js").read_text(encoding="utf-8").strip()
    body = text[text.index("{"): text.rindex("}") + 1]
    return json.loads(body)


ENTRY_RE = re.compile(
    r'\{\s*key:\s*"(?P<key>[^"]+)"(?P<rest>[^}]*)\}'
)
DISPLAY_RE = re.compile(r'displayName:\s*"([^"]*)"')


def load_page_config() -> dict:
    """Map project key -> section name, by reading assets/page-config.js.

    A light regex parse rather than a JS engine: the file is hand-edited in a
    fixed one-entry-per-line shape, and anything it can't read just falls back
    to a home-page back link.
    """
    text = (ASSETS_DIR / "page-config.js").read_text(encoding="utf-8")
    sections = {}
    for name in SECTION_PAGES:
        match = re.search(rf"\b{name}\s*:\s*\[(.*?)\]", text, re.S)
        if not match:
            continue
        for entry in ENTRY_RE.finditer(match.group(1)):
            display = DISPLAY_RE.search(entry.group("rest"))
            sections[entry.group("key")] = {
                "section": name,
                "displayName": display.group(1) if display else None,
            }
    return sections


def load_details() -> dict:
    """What each project's entry in assets/project-details.js says about it,
    read with regexes rather than a JS engine, like load_page_config: its
    overview, the clip it leads with (`hero`), and whether it has a write-up
    of its own (`story`)."""
    text = (ASSETS_DIR / "project-details.js").read_text(encoding="utf-8")
    starts = [(m.start(), m.group(1)) for m in re.finditer(r'^  "([a-z0-9]+/[a-z0-9]+)": \{', text, re.M)]
    out = {}
    for i, (pos, key) in enumerate(starts):
        block = text[pos: starts[i + 1][0] if i + 1 < len(starts) else len(text)]
        ov = re.search(r'\boverview:\s*"((?:[^"\\]|\\.)*)"', block)
        hero = re.search(r'\bhero:\s*"([^"]+)"', block)
        out[key] = {
            "overview": ov.group(1).replace('\\"', '"') if ov else "",
            "hero": hero.group(1) if hero else None,
            "story": bool(re.search(r'\bstory:\s*\[', block)),
        }
    return out


def load_curated() -> dict:
    text = (ASSETS_DIR / "curated-media.js").read_text(encoding="utf-8")
    return json.loads(text[text.index("{"): text.rindex("}") + 1])


def share_image_for(key, data, details, curated) -> str:
    """The project's own picture for a link preview: the poster of the clip it
    leads with, else its hand-picked plate, else its thumbnail."""
    c = curated.get(key, {})
    hero = details.get("hero")
    if hero and hero in c.get("items", {}):
        item = c["items"][hero]
        path = item.get("poster") or item.get("src")
        if path and not path.endswith(".mp4"):
            return f"{SITE_URL}/{path}"
    if c.get("thumbs"):
        return f"{SITE_URL}/{c['thumbs'][0]}"
    if data.get("thumb"):
        return f"{SITE_URL}/{data['thumb']}"
    return SHARE_IMAGE


def escape(text: str) -> str:
    return (str(text).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def main() -> int:
    manifest = load_manifest()
    page_config = load_page_config()
    all_details = load_details()
    curated = load_curated()
    indexed = []
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    seen_slugs = {}
    written = []

    for key, data in manifest.items():
        if key in RETIRED:
            print(f"  skipped {key} (retired)")
            continue
        slug = key.split("/")[1]
        if slug in seen_slugs:
            print(f"  ERROR: slug collision — {key} and {seen_slugs[slug]} both want "
                  f"projects/{slug}.html. Rename one of the source folders.")
            return 1
        seen_slugs[slug] = key

        placement = page_config.get(key)
        if placement:
            back_href, back_label = SECTION_PAGES[placement["section"]]
        else:
            back_href, back_label = "index.html", "home"
            print(f"  note: {key} is on no list page (add it to assets/page-config.js) — "
                  f"its page links back home")

        title = (placement or {}).get("displayName") or data.get("name") or slug
        # The tag names who the work was made with. "Jishnu" is the folder for
        # solo work, and on his own site that says nothing, so it is left off.
        category = data.get("category") or ""
        if category.lower() == "jishnu":
            category = ""
        # A project with no write-up of its own yet stays reachable but is kept
        # out of search and out of the sitemap until it has one.
        details = all_details.get(key, {"overview": "", "hero": None, "story": False})
        robots = "" if details["story"] else '\n  <meta name="robots" content="noindex">'
        if details["story"]:
            indexed.append(f"projects/{slug}.html")
        page = TEMPLATE.format(
            marker=MARKER,
            key=escape(key),
            slug=slug,
            title=escape(title),
            category=escape(category),
            description=escape(details["overview"] or f"{title} — a project by Jishnu Roy Chaudhury."),
            overview=escape(details["overview"]),
            robots=robots,
            back_href=back_href,
            back_label=back_label,
            site_url=SITE_URL,
            share_image=share_image_for(key, data, details, curated),
        )

        out_path = OUT_DIR / f"{slug}.html"
        out_path.write_text(page, encoding="utf-8")
        written.append(out_path.name)
        print(f"  wrote projects/{slug}.html  ({title})")

    # Drop pages for projects that no longer exist, leaving hand-written files.
    for stale in sorted(OUT_DIR.glob("*.html")):
        if stale.name in written:
            continue
        if MARKER in stale.read_text(encoding="utf-8"):
            stale.unlink()
            print(f"  removed stale projects/{stale.name}")
        else:
            print(f"  skipped projects/{stale.name} (not generated by this script)")

    # sitemap.xml: the site's own pages and every project page with a write-up.
    urls = [f"{SITE_URL}/{p}" for p in SITE_PAGES] + [f"{SITE_URL}/{p}" for p in sorted(indexed)]
    sitemap = ('<?xml version="1.0" encoding="UTF-8"?>\n'
               '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
               + "".join(f"  <url><loc>{u}</loc></url>\n" for u in urls)
               + "</urlset>\n")
    (ROOT / "sitemap.xml").write_text(sitemap, encoding="utf-8")
    print(f"Wrote sitemap.xml ({len(urls)} URLs; {len(written) - len(indexed)} unwritten projects left out)")

    print(f"\nWrote {len(written)} project pages to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
